### ISSUE TITLE
Sorting Array Problem 

### ISSUE THREAD

**Issue by SwanandBhuskute** [SwanandBhuskute/Leetcode_and_GFG#4]
Q. Create an array of five mobile phone objects by reading the data from the user. Use the static method sort_mobileDetails() to read the array of mobile objects and sort them according to the company name. Display the sorted array of objects using the display_mobileDetails Method.

Add a C/C++/Java/Python solution.

**Comment by Bishal-Choudhury** [comment]
hello, I would like to contribute to this issue.
