### ISSUE TITLE
String Array Question

### ISSUE THREAD

**Issue by SwanandBhuskute** [SwanandBhuskute/Leetcode_and_GFG#6]
Read the names of students who scored 8.0 cgpa and store it in a String array. Check if the name entered by the user is present or not. If present, display as "Name is 8.0 pointer", otherwise display as "Name is not a 8.0 pointer".

Add solution in C/C++/Java/Python.

**Comment by jeetjawale** [comment]
@SwanandBhuskute I would like to contribute...

**Comment by rhymasharma** [comment]
May I work on this?

**Comment by SwanandBhuskute** [comment]
@jeetjawale ok continue...
